// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

//import  from "./.react_controller.js.swp"
//application.register("", )

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ReactController from "./react_controller.js"
application.register("react", ReactController)
